"""Initial Migration

Revision ID: 354edee5cb08
Revises: 
Create Date: 2023-05-21 19:08:37.446345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354edee5cb08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_owners_email'), 'vehicle_owners', ['email'], unique=True)
    op.create_index(op.f('ix_vehicle_owners_id'), 'vehicle_owners', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['vehicle_owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_company'), 'vehicles', ['company'], unique=False)
    op.create_index(op.f('ix_vehicles_email'), 'vehicles', ['email'], unique=True)
    op.create_index(op.f('ix_vehicles_first_name'), 'vehicles', ['first_name'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_last_name'), 'vehicles', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_last_name'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_first_name'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_email'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_company'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_vehicle_owners_id'), table_name='vehicle_owners')
    op.drop_index(op.f('ix_vehicle_owners_email'), table_name='vehicle_owners')
    op.drop_table('vehicle_owners')
    # ### end Alembic commands ###
