"""Initial Migration

Revision ID: 9e482e1f149b
Revises: 
Create Date: 2023-05-29 03:30:00.275961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e482e1f149b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_owners_address'), 'vehicle_owners', ['address'], unique=False)
    op.create_index(op.f('ix_vehicle_owners_city'), 'vehicle_owners', ['city'], unique=False)
    op.create_index(op.f('ix_vehicle_owners_document'), 'vehicle_owners', ['document'], unique=True)
    op.create_index(op.f('ix_vehicle_owners_email'), 'vehicle_owners', ['email'], unique=True)
    op.create_index(op.f('ix_vehicle_owners_id'), 'vehicle_owners', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_owners_phone'), 'vehicle_owners', ['phone'], unique=False)
    op.create_index(op.f('ix_vehicle_owners_state'), 'vehicle_owners', ['state'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('license_plate_city', sa.String(), nullable=True),
    sa.Column('license_plate_state', sa.String(), nullable=True),
    sa.Column('v_type', sa.String(), nullable=True),
    sa.Column('v_make', sa.String(), nullable=True),
    sa.Column('v_model', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('renavam', sa.String(), nullable=True),
    sa.Column('chassis', sa.String(), nullable=True),
    sa.Column('axles_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['vehicle_owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_axles_number'), 'vehicles', ['axles_number'], unique=False)
    op.create_index(op.f('ix_vehicles_chassis'), 'vehicles', ['chassis'], unique=False)
    op.create_index(op.f('ix_vehicles_color'), 'vehicles', ['color'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=False)
    op.create_index(op.f('ix_vehicles_license_plate_city'), 'vehicles', ['license_plate_city'], unique=False)
    op.create_index(op.f('ix_vehicles_license_plate_state'), 'vehicles', ['license_plate_state'], unique=False)
    op.create_index(op.f('ix_vehicles_renavam'), 'vehicles', ['renavam'], unique=False)
    op.create_index(op.f('ix_vehicles_v_make'), 'vehicles', ['v_make'], unique=False)
    op.create_index(op.f('ix_vehicles_v_model'), 'vehicles', ['v_model'], unique=False)
    op.create_index(op.f('ix_vehicles_v_type'), 'vehicles', ['v_type'], unique=False)
    op.create_index(op.f('ix_vehicles_year'), 'vehicles', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_year'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_v_type'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_v_model'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_v_make'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_renavam'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_license_plate_state'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_license_plate_city'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_color'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_chassis'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_axles_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_vehicle_owners_state'), table_name='vehicle_owners')
    op.drop_index(op.f('ix_vehicle_owners_phone'), table_name='vehicle_owners')
    op.drop_index(op.f('ix_vehicle_owners_id'), table_name='vehicle_owners')
    op.drop_index(op.f('ix_vehicle_owners_email'), table_name='vehicle_owners')
    op.drop_index(op.f('ix_vehicle_owners_document'), table_name='vehicle_owners')
    op.drop_index(op.f('ix_vehicle_owners_city'), table_name='vehicle_owners')
    op.drop_index(op.f('ix_vehicle_owners_address'), table_name='vehicle_owners')
    op.drop_table('vehicle_owners')
    # ### end Alembic commands ###
